name: recognize_text
description: "recognize text from audio"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-129.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ionicons: ^0.1.2
  flutter_inset_box_shadow: ^1.0.8
  animated_music_indicator: ^0.0.6

  http: ^1.2.1
  speech_to_text: ^6.6.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700

  assets:
    - assets/images/facebook.png
    - assets/images/google.png

